# models/staging/stripe/schema.yml
version: 2

sources:
  - name: stripe
    schema: bronze
    tables:
      - name: stripe_subscriptions
      - name: stripe_customers
      - name: stripe_charges

models:
  - name: stg_subscriptions
    freshness:
      error_after: { count: 12, period: hour }
    loaded_at_field: created_at
    columns:
      - name: subscription_id
        tests: [not_null, unique]

  - name: stg_customers
    freshness:
      error_after: { count: 12, period: hour }
    loaded_at_field: created_at
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_charges
    freshness:
      error_after: { count: 12, period: hour }
    loaded_at_field: created_at
    columns:
      - name: charge_id
        tests: [not_null, unique]
      - name: subscription_id
        tests: [not_null]
